## Learning Numpy. The Hard Way. 

Вам нужно выполнить упражнения по Numpy.


#### Задание 1.
```python
 # Q. Import numpy as np and print the version number.
```

In [3]:
import numpy as np
import platform
print(platform.python_version())

3.8.8


#### Задание 2.
```python
# Q. Create a 1D array of numbers from 0 to 9

# Desired Output
# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Задание 3.
```python
 # Q. Create a 3×3 numpy array of all True’s
```

In [27]:
np.vander([True,True,True], 3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### Задание 4.
```python
# Q. Extract all odd numbers from arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# > array([1, 3, 5, 7, 9])
```

In [32]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

new_odd_array = arr[1::2]
new_odd_array

Input


array([1, 3, 5, 7, 9])

#### Задание 5.
```python
# Q. Replace all odd numbers in arr with -1
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [42]:
arr = [-1 if x % 2 else x for x in arr]
arr

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

#### Задание 6.
```python
# Q. Replace all odd numbers in arr with -1 without changing arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input")
arr

# Desired Output
# out #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [43]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_array = [-1 if x % 2 else x for x in arr]
print(new_array,arr)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1] [0 1 2 3 4 5 6 7 8 9]


#### Задание 7.
```python
# Q. Convert a 1D array to a 2D array with 2 rows
# Input 
arr = np.arange(10)
print("Input")
arr

# Desired Output
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])
```

In [55]:
arr = np.arange(10)
arr = arr.reshape(2, -1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Задание 8.
```python
# Q. Stack arrays a and b vertically
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a
b

# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [60]:
print(np.vstack([a, b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Задание 9.
```python
# Q. Stack the arrays a and b horizontally.
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Desired Output
# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [61]:
print(np.hstack([a, b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Задание 10.
```python
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input
print("Input")
a = np.array([1,2,3])
a

# Desired Output
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [63]:
a = np.r_[np.repeat(a, 3), np.tile(a, 3)]
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Задание 11.
```python
# Q. Get the common items between a and b

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# array([2, 4])
```

In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
new = np.intersect1d(a,b)
new

array([2, 4])

#### Задание 12.
```python
# Q. From array a remove all items present in array b

# Input
print("Input")
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a
b

# Desired Output
# array([1,2,3,4])
```

In [67]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


#### Задание 13.
```python
# Q. Get the positions where elements of a and b match

# Input
print("Input")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a
b

# Desired Output
# > (array([1, 3, 5, 7]),)
```

In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
new = np.where(a==b)
new

(array([1, 3, 5, 7], dtype=int64),)

#### Задание 14.
```python
# Q. Get all items between 5 and 10 from a.

# Input
print("Input")
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

# Desired Output
# (array([6, 9, 10]),)
```

In [77]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

#### Задание 15.
```python
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input

def maxx(x, y):
    """
    Get the maximum of two items
    """
    
    if x >= y:
        return x
    else:
        return y
print("Result of the maxx function")
maxx(1, 5)

print("Input")
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
a
b

# Desired Output
# pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [71]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
max = np.vectorize(max, otypes=[int])
max(a,b)
max = np.vectorize(max, otypes=[float])
max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

#### Задание 16.
```python
# Q. Swap columns 1 and 2 in the array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [82]:
arr = np.arange(9).reshape(3,3)
arr
arr = arr[:, [1,0,2]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### Задание 17.
```python
# Q. Swap rows 1 and 2 in the array arr:

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [4]:

arr = np.arange(9).reshape(3,3)
arr
arr = arr[ [1,0,2],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### Задание 18.
```python
# Q. Reverse the rows of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [6]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### Задание 19.
```python
# Q. Reverse the columns of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [7]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

#### Задание 20.
```python
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
```

In [18]:
arr = np.random.uniform(5,10, size=(5,3))
arr

array([[8.39173715, 8.95426262, 7.98244743],
       [9.66084582, 7.88686953, 6.47434012],
       [8.14534578, 5.87290831, 5.72335165],
       [7.64983064, 9.3641085 , 9.34715032],
       [7.51668069, 7.6096357 , 6.75968871]])