## Learning Numpy. The Hard Way. Part 2.

Вам нужно выполнить следующую часть упражнений по Numpy.


In [19]:
import numpy as np
import sys
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=3, suppress=False, threshold=1000, formatter=None)

#### Задание 21.
```python
# Q. Print or show only 3 decimal places of the numpy array rand_arr.

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)

# Input
print("Input")
rand_arr = np.random.random((5,3))
rand_arr
```

In [5]:
rand_arr = np.random.random((5,3))
rand_arr


array([[0.243, 0.088, 0.546],
       [0.696, 0.965, 0.269],
       [0.708, 0.704, 0.13 ],
       [0.274, 0.419, 0.354],
       [0.905, 0.844, 0.018]])

#### Задание 22.
```python
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)

# Input
print("Input")
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

# Desired Output
# > array([[ 0.000543,  0.000278,  0.000425],
# >        [ 0.000845,  0.000005,  0.000122],
# >        [ 0.000671,  0.000826,  0.000137]])
```

In [11]:
np.set_printoptions(suppress=True,precision=4) 
rand_arr = np.random.random([3,3])/1e3
rand_arr


array([[0.0001, 0.0003, 0.0009],
       [0.0005, 0.0005, 0.0009],
       [0.0009, 0.0004, 0.0006]])

#### Задание 23.
```python
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)

# Input
print("Input")
a = np.arange(15)
a

# Desired Output
# > array([ 0,  1,  2, ..., 12, 13, 14])
```

In [14]:
np.set_printoptions(edgeitems=3,infstr='inf',threshold=6, linewidth=75, nanstr='nan', precision=8, suppress=False,  formatter=None)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

#### Задание 24.
```python
# Q. Print the full numpy array a without truncating.

# Input
print("Input")
np.set_printoptions(threshold=6)
a = np.arange(15)
a

# Desired Output
# > array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

In [22]:
np.set_printoptions(threshold=sys.maxsize)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Задание 25.
```python
# Q. Import the iris dataset keeping the text intact.

# Input
# Use the iris dataset provided
print_files()

# All the available options of the numpy genfromtxt function
# numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, 
#                    skip_footer=0, converters=None, missing_values=None, filling_values=None, 
#                    usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\]^{|}~", 
#                    replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', 
#                    unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')[source]
```

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

#### Задание 26.
```python
# Q. Extract the text column species from the 1D iris imported in previous question.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [28]:
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:]

(150,)


<ipython-input-28-91f1766eab03>:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

#### Задание 27.
```python
# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [29]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

#### Задание 28.
```python
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [34]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mean, median, standard_deviation = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print('mean=',mean, 'median=',median, 'sd=',standard_deviation)

mean= 5.843333333333334 median= 5.8 sd= 0.8253012917851409


#### Задание 29.
```python
# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [36]:
max, min = sepallength.max(), sepallength.min()
n = (sepallength - min)/(max - min)
n

array([0.222, 0.167, 0.111, 0.083, 0.194, 0.306, 0.083, 0.194, 0.028,
       0.167, 0.306, 0.139, 0.139, 0.   , 0.417, 0.389, 0.306, 0.222,
       0.389, 0.222, 0.306, 0.222, 0.083, 0.222, 0.139, 0.194, 0.194,
       0.25 , 0.25 , 0.111, 0.139, 0.306, 0.25 , 0.333, 0.167, 0.194,
       0.333, 0.167, 0.028, 0.222, 0.194, 0.056, 0.028, 0.194, 0.222,
       0.139, 0.222, 0.083, 0.278, 0.194, 0.75 , 0.583, 0.722, 0.333,
       0.611, 0.389, 0.556, 0.167, 0.639, 0.25 , 0.194, 0.444, 0.472,
       0.5  , 0.361, 0.667, 0.361, 0.417, 0.528, 0.361, 0.444, 0.5  ,
       0.556, 0.5  , 0.583, 0.639, 0.694, 0.667, 0.472, 0.389, 0.333,
       0.333, 0.417, 0.472, 0.306, 0.472, 0.667, 0.556, 0.361, 0.333,
       0.333, 0.5  , 0.417, 0.194, 0.361, 0.389, 0.389, 0.528, 0.222,
       0.389, 0.556, 0.417, 0.778, 0.556, 0.611, 0.917, 0.167, 0.833,
       0.667, 0.806, 0.611, 0.583, 0.694, 0.389, 0.417, 0.583, 0.611,
       0.944, 0.944, 0.472, 0.722, 0.361, 0.944, 0.556, 0.667, 0.806,
       0.528, 0.5  ,

#### Задание 30.
```python
# Q. Compute the softmax score of sepallength.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [37]:
def softmax(y):
    x = np.exp(y - np.max(y))
    return x / x.sum(axis=0)

print(softmax(sepallength))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


#### Задание 31.
```python
# Q. Find the 5th and 95th percentile of iris's sepallength

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [38]:
low = 5
high = 95
np.percentile(sepallength, q=[low, high])

array([4.6  , 7.255])

#### Задание 32.
```python
# Q. Insert np.nan values at 20 random positions in iris_2d dataset

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [45]:
np.random.seed(100)
iris_2d[np.random.choice((iris_2d.shape[0]), 20), np.random.choice((iris_2d.shape[1]), 20)] = np.nan
iris_2d[:20]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, nan, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [nan, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3]])

#### Задание 33.
```python
#### Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [47]:
print("number: ", np.isnan(iris_2d[:, 0]).sum())
print("Position : ", np.where(np.isnan(iris_2d[:, 0])))

number:  4
Position :  (array([14, 34, 79, 87], dtype=int64),)


#### Задание 34.
```python
# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [48]:
iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

#### Задание 35.
```python
# Q. Select the rows of iris_2d that does not have any nan value.

# Input
# Use the titanic dataset provided
print_files()

# set original print statements
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)
```

In [53]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1)]

array([[5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3

#### Задание 36.
```python
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [60]:
np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1]

nan

#### Задание 37.
```python
# Q. Find out if iris_2d has any missing values.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [61]:
np.isnan(iris_2d).any()

True

#### Задание 38.
```python
# Q. Replace all ccurrences of nan with 0 in numpy array

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [63]:
iris_2d[np.isnan(iris_2d)]=0
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 0. , 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

#### Задание 39.
```python
# Q. Find the unique values and the count of unique values in iris's species

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [67]:
sp = np.array([row.tolist()[4] for row in iris])

np.unique(sp, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

#### Задание 40.
```python
# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [73]:
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'),[1, 2, 3, 4, 5, 6])

# Map it to respective category
label_map = {1: 'small',2: 'small', 3: 'medium', 4:'medium', 5: 'large', 6: 'large'}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:]

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu