## Learning Numpy. The Hard Way. Part 3.

Вам нужно выполнить __последнюю часть__ упражнений по Numpy.


In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=3, suppress=False, threshold=1000, formatter=None)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

#### Задание 41.
```python
# Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [27]:
new_col_sepal_length = iris_2d[:, 0]
new_col_petallength = iris_2d[:, 2]
volume = (np.pi * new_col_petallength * (new_col_sepal_length**2))/3
volume
volume = volume[:, np.newaxis]
volume
new_volume = np.hstack([iris_2d, volume])
print(np.array_str(new_volume, precision=2, suppress_small=True))

[[  5.1    3.5    1.4    0.2   38.13]
 [  4.9    3.     1.4    0.2   35.2 ]
 [  4.7    3.2    1.3    0.2   30.07]
 [  4.6    3.1    1.5    0.2   33.24]
 [  5.     3.6    1.4    0.2   36.65]
 [  5.4    3.9    1.7    0.4   51.91]
 [  4.6    3.4    1.4    0.3   31.02]
 [  5.     3.4    1.5    0.2   39.27]
 [  4.4    2.9    1.4    0.2   28.38]
 [  4.9    3.1    1.5    0.1   37.71]
 [  5.4    3.7    1.5    0.2   45.8 ]
 [  4.8    3.4    1.6    0.2   38.6 ]
 [  4.8    3.     1.4    0.1   33.78]
 [  4.3    3.     1.1    0.1   21.3 ]
 [  5.8    4.     1.2    0.2   42.27]
 [  5.7    4.4    1.5    0.4   51.04]
 [  5.4    3.9    1.3    0.4   39.7 ]
 [  5.1    3.5    1.4    0.3   38.13]
 [  5.7    3.8    1.7    0.3   57.84]
 [  5.1    3.8    1.5    0.3   40.86]
 [  5.4    3.4    1.7    0.2   51.91]
 [  5.1    3.7    1.5    0.4   40.86]
 [  4.6    3.6    1.     0.2   22.16]
 [  5.1    3.3    1.7    0.5   46.3 ]
 [  4.8    3.4    1.9    0.2   45.84]
 [  5.     3.     1.6    0.2   41.89]
 [  5.     3

#### Задание 42.
```python
# Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [36]:
species = iris[:, 4]
np.random.seed(100)
all = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(all, iris.shape[0], p=[0.5, 0.25, 0.25])
species_out

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versic

#### Задание 43.
```python
# Q. What is the value of second longest petallength of species setosa

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [31]:
second_longest_petallength = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')
np.unique(np.sort(second_longest_petallength ))[-2]

1.7

#### Задание 44.
```python
# Q. Sort the iris dataset based on sepallength column.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [54]:
#sepallength iris[:,0]
print(iris[iris[:,0].argsort()][:10])
#np.sort(iris[iris[:,0]])

IndexError: arrays used as indices must be of integer (or boolean) type

#### Задание 45.
```python
# Q. Find the most frequent value of petal length (3rd column) in iris dataset.

# Input
# Use the iris dataset provided
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```

In [55]:
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


#### Задание 46.
```python
# Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
```

In [58]:
np.argwhere(iris[:, 3].astype('float') > 1.0)[0]

array([50], dtype=int64)

#### Задание 47.
```python
# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
# Input
print("Input")
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

```

In [59]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


#### Задание 48.
```python
# Q. Get the positions of top 5 maximum values in a given array a.

# Input
print("Input")
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a
```

In [61]:
a = np.random.uniform(1,50, 20)
np.sort(a)[-5:]

array([37.382, 38.687, 42.767, 44.358, 48.775])

#### Задание 49.
```python
# Q. Compute the counts of unique values row-wise.

# Input
print("Input")
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

# Desired Output
# > [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
# >  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
# >  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
# >  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
# >  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
# >  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

# Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
# For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.
```

In [63]:
def counts_of_all_values_rowwise(arr):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr]
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr)] for a, b in num_counts_array])

arr = np.random.randint(1,11,size=(6, 10))
counts_of_all_values_rowwise(arr)

[[0, 2, 2, 1, 2, 0, 1, 0, 2, 0],
 [1, 2, 2, 1, 0, 2, 0, 2, 0, 0],
 [0, 2, 2, 0, 1, 2, 2, 0, 0, 1],
 [1, 2, 1, 1, 0, 1, 1, 2, 0, 1],
 [1, 0, 0, 2, 1, 1, 3, 1, 1, 0],
 [3, 2, 1, 2, 0, 1, 1, 0, 0, 0]]

#### Задание 50.
```python
# Q. Convert array_of_arrays into a flat linear 1d array.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr
```

In [65]:
arr = np.arange(9).reshape(3,3)

array_of_arrays = np.array([arr, arr, arr])
array_of_arrays

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Задание 51.
```python
# Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

# Input
print("Input")
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

# Desired Output
# > array([[ 0.,  1.,  0.],
# >        [ 0.,  0.,  1.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 1.,  0.,  0.]])
```

In [66]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

#### Задание 52.
```python
# Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
# species_small = np.sort(np.random.choice(species, size=20))
# species_small
# > array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
# >        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
# >       dtype='<U15')


# Desired Output
# > [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]
```

In [3]:
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4]


#### Задание 53.
```python
# Q. Create group ids based on a given categorical variable. Use the following sample from iris species as input

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
# species_small = np.sort(np.random.choice(species, size=20))
# species_small
# > array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
# >        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
# >        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
# >        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
# >       dtype='<U15')

# Desired Output
# > [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
```

In [4]:
output = []
uniqs = np.unique(species_small)

for val in uniqs: 
    for s in species_small[species_small==val]: 
        groupid = np.argwhere(uniqs == s).tolist()[0][0] 
        output.append(groupid)

print(output)

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]


#### Задание 54.
```python
# Q. Create the ranks for the given numeric array a.

# Input
print("Input")
np.random.seed(10)
a = np.random.randint(20, size=10)
a

# Desired Output
# [4 2 6 0 8 7 9 3 5 1]
```

In [5]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a.argsort().argsort())


[4 2 6 0 8 7 9 3 5 1]


#### Задание 55.
```python
# Q. Create a rank array of the same shape as a given numeric array a.

# Input
print("Input")
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
a

# Desired Output
# > [[4 2 6 0 8]
# >  [7 9 3 5 1]]
```

In [11]:
np.random.seed(10)
a = np.random.randint(20, size=10)

print(a.ravel().argsort().argsort().reshape(2,5))


[[4 2 6 0 8]
 [7 9 3 5 1]]


#### Задание 56.
```python
# Q. Compute the maximum for each row in the given array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

In [12]:
a = np.random.randint(1,10, [5,3])
np.amax(a, axis=1)

array([9, 5, 9, 9, 7])

#### Задание 57.
```python
# Q. Compute the min-by-max for each row for given 2d numpy array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

In [13]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.444, 0.125, 0.5  , 1.   , 0.111])

#### Задание 58.
```python
# Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

# Desired Output
# > [False  True False  True False False  True  True  True  True]
```

In [16]:
a = np.random.randint(0, 5, 10)
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False

print(out)

[False False False False  True  True  True  True  True  True]


#### Задание 59.
```python
# Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

# Input
# Use the iris dataset provided
print("Input")
print_files()

# Use this if you are working on your local machine
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Desired Output
# > [[b'Iris-setosa', 3.418],
# >  [b'Iris-versicolor', 2.770],
# >  [b'Iris-virginica', 2.974]]
```

In [18]:
numeric_column = iris[:, 1].astype('float') 
grouping_column = iris[:, 4] 



output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

#### Задание 60.
```python
# Q. Import the image from the following URL and convert it to a numpy array.

# Input
print("Input")
print_files()

# Use this if you are working on your local machine
# URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
```

In [20]:
from io import BytesIO
from PIL import Image
import PIL, requests


URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

I = Image.open(BytesIO(response.content))


arr = np.asarray(I)
arr


array([[[  9,  72, 125],
        [  9,  72, 125],
        [  9,  72, 125],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [  9,  72, 125],
        [ 10,  73, 126],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [ 10,  73, 126],
        [ 10,  73, 126],
        ...,
        [ 44, 105, 150],
        [ 45, 106, 151],
        [ 45, 106, 151]],

       ...,

       [[ 21,  41,  50],
        [ 29,  51,  64],
        [ 28,  54,  69],
        ...,
        [ 27,  58,  79],
        [ 22,  53,  74],
        [ 19,  47,  69]],

       [[ 27,  51,  63],
        [ 29,  55,  68],
        [ 27,  56,  72],
        ...,
        [ 33,  70,  97],
        [ 27,  64,  91],
        [ 22,  57,  85]],

       [[ 18,  45,  56],
        [ 20,  48,  62],
        [ 21,  52,  70],
        ...,
        [ 15,  51,  77],
        [ 12,  48,  74],
        [ 11,  45,  72]]

#### Задание 61.
```python
# Q. Drop all nan values from a 1D numpy array

# Input
print("Input")
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a

# Desired Output
# array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [23]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]
#a.drop(np.isnan(a))


array([1., 2., 3., 5., 6., 7.])

#### Задание 62.
```python
# Q. Compute the euclidean distance between two arrays a and b.

# Input
print("Input")
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
a
b
```

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
dist

6.708203932499369

#### Задание 63.
```python
# Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

# Input
print("Input")
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a

# Desired Output
# > array([2, 5])
# where, 2 and 5 are the positions of peak values 7 and 6.
```

In [30]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
diff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(diff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

#### Задание 64.
```python
# Q. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

# Input
print("Input")
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
a_2d
b_1d

# Desired Output
# > [[2 2 2]
# >  [2 2 2]
# >  [2 2 2]]
```

In [34]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


#### Задание 65.
```python
# Q. Find the index of 5th repetition of number 1 in x.

# Input
print("Input")
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
x
```

In [35]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

np.where(x == 1)[0][n-1]

8

#### Задание 66.
```python
# Q. Convert numpy's datetime64 object to datetime's datetime object

# Input
print("Input")
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64
```

In [37]:
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

#### Задание 67.
```python
# Q. Compute the moving average of window size 3, for the given 1D array.

# Input
print("Input")
np.random.seed(100)
a = np.random.randint(10, size=10)
a
```

In [38]:
np.random.seed(100)
a = np.random.randint(10, size=10)
np.convolve(a, np.ones(3)/3, mode='valid')

array([6.333, 6.   , 5.667, 4.667, 3.667, 2.   , 3.667, 3.   ])

#### Задание 68.
```python
# Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
```

In [39]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

#### Задание 69.
```python
# Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

# Input
print("Input")
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
dates
```

In [9]:
#69
print("Input")
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
dates

outoutput = []
for date, d in zip(dates, np.diff(dates)):
    outoutput.append(np.arange(date, (date+d)))

filled_in = np.array(outoutput).reshape(-1)

output = np.hstack([filled_in, dates[-1]])
output


Input


array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

#### Задание 70.
```python
# Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

# Input
print("Input")
arr = np.arange(15) 
arr

# Desired Output
# > [[ 0  1  2  3]
# >  [ 2  3  4  5]
# >  [ 4  5  6  7]
# >  [ 6  7  8  9]
# >  [ 8  9 10 11]
# >  [10 11 12 13]]
```

In [7]:
#70
#print("Input")
array_given = np.arange(15) 
array_given
def gen_using_met_strides(array_given, strides , length ):
    n_strides = ((array_given.size-length)//strides) + 1
    return np.array([array_given[s:(s+length)] for s in np.arange(0, n_strides*strides, strides)])

print(gen_using_met_strides(np.arange(15), strides = 2, length = 4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
